### PR TITLE
Update deploy script

### PR DESCRIPTION
**Pull request by modos189**
Migration scripts for deployment in localbuildsettings.py.
Fix update URL/downloadURL https://github.com/IITC-CE/ingress-intel-total-conversion/issues/32 https://github.com/IITC-CE/ingress-intel-total-conversion/pull/53 https://github.com/IITC-CE/ingress-intel-total-conversion/pull/86

Commit to master leads to release build and upload to site.
Creating a new GitHub Release leads to build release version, uploading to site and attaching archives to GitHub Release https://github.com/IITC-CE/ingress-intel-total-conversion/issues/56

### CODE REVIEW

**Comment by johnd0e** [comment]
After I've pulled it into `test-builds` branch I saw that [both jobs started](https://travis-ci.org/IITC-CE/ingress-intel-total-conversion/builds/492746864):
- Test-builds
- Release

As I was not sure that it is intended I just cancelled Release job in order to prevent deploy.

**Comment by modos189** [comment]
Fixed on second attempt =(

**Comment by johnd0e** [comment]
There is unneeded additional slash in url, see e.g. https://iitc.modos189.ru/build/test/plugins/reso-energy-pct-in-portal-detail.user.js
```
// @updateURL      https://iitc.modos189.ru/build/test//plugins/reso-energy-pct-in-portal-detail.meta.js
// @downloadURL    https://iitc.modos189.ru/build/test//plugins/reso-energy-pct-in-portal-detail.user.js
```

**Comment by modos189** [comment]
Fixed

**Pull request merged**
