### PR TITLE
build_plugin.py: some code can be placed outside of wrapper

### LINKED ISSUE #354: can't put code outside of wrapper with new build system
i need to place some code outside of wrapper() since i have various things running in GM sandbox that don't want to expose.

Functions that need to be accessible are placed inside wrapper everything else is outside wrapper

with the old build system i just placed the code before the @@PLUGINSTART@@ and could control where my code is running.

### PR DESCRIPTION
**Pull request by johnd0e**
Close #354

To leave some code out of wrapper use special marker (on separate line):

```js
'this_is_unwrapped';
/*wrapped-from-here*/
```

### CODE REVIEW

**Comment by johnd0e** [comment]
@Aradiv

Please check if it works as expected by you.

**Comment by johnd0e** [comment]
It seems that #358 has better solution

**Review by modos189 — APPROVED** [review]
Looks bad, but as a temporary solution is acceptable. Especially, as I understand it, after #358 there will simply be no need to comment /*wrapped-from-here*/ - it will work without this comment.

**Comment by johnd0e** [comment]
No, #358 was initially based on wrong assumption.
It cannot be used in GreaseMonkey and IITC-Button.

**Pull request merged**
