### PR TITLE
A cross link autodetect tool

### PR DESCRIPTION
**Pull request by magicbug2013**
When you click on a line, it will automatically find all the corss links and identify them.

### CODE REVIEW

**Comment by johnd0e** [comment]
Thank you for this contribution.
Please note that we still avoid using ecmascript 2015+ features (#47).
This includes `const`, promises, `await`/`async`, arrow functions, destructuring assignment etc.

**Comment by johnd0e** [comment]
`varφ`, `varλ`, `varθ`, `varδ`/`10`/`20`, `varΣθ` (space missed)

And some style issues (https://github.com/IITC-CE/ingress-intel-total-conversion/issues/39#issuecomment-455122280), like `semi`, `eqeqeq`, `quotes`.

**Comment by magicbug2013** [comment]
OK, I'll try to fix these.

**Comment by johnd0e** [comment]
There was no need to close the PR, usually it's better just to fix your original branch.

Also note that instead of `markerTemplate` you could use upcoming #96.

**Pull request closed without merging**
