### PR TITLE
Draw-Tools

### PR DESCRIPTION
**Pull request by MysticJay**
Imported Zaso's Draw-Tools-Plus features "EmptyDrawFields (EDF)" and merge-function.

### CODE REVIEW

**Comment by johnd0e** [comment]
@MysticJay You should try to do minimal changes and avoid changing parts that already changed by other PR. If you need that change later - better make it later. Otherwise you will have to solve same conflicts over and over again

**Comment by johnd0e** [comment]
Please consider commens from #223

**Comment by MysticJay** [comment]
That's exactly what I did... This PR does ONLY include merge and EDF

**Comment by MysticJay** [comment]
Do we have "export to file" code somewhere?

**Comment by modos189** [comment]
Is this PR still relevant or has it been replaced by other PRs?

**Comment by MysticJay** [comment]
This PR has been split into two on request.
See PR#377 (EDF) and PR#406 (Merge)

**Pull request closed without merging**
