### PR TITLE
Mission Field-Trip positions

### PR DESCRIPTION
**Pull request by McBen**
a) show FieldTrip waypoints in Mission path ( 6984bf1 )
  position data wasn't filled
b) fix error when mission data is empty ( 4773f52 )
  missing check for empty data results in exception

+ code-style fixes

### CODE REVIEW

**Comment by johnd0e** [comment]
Conflicts

**Comment by modos189** [comment]
Now when viewing both the list of mission portals and the route on the map, the Field Trip points are displayed. In this part I do not see any difference with this PR

**Comment by McBen** [comment]
make sure to clear plugins-missions-missioncache ( `localStorage.removeItem("plugins-missions-missioncache")` )
mission plugin stores loaded+parsed data

without PR
mission4

with PR
mission3

**Comment by McBen** [comment]
without IITC

mission1

**Review by modos189 — APPROVED** [review]
Ok, I see. Thanks

**Pull request merged**
