### PR TITLE
added upload to the drowtool

### PR DESCRIPTION
**Pull request by durck**

### CODE REVIEW

**Comment by johnd0e** [comment]
Ok, I see now. Thank your for this concept.

Actually, it's not necessary to modify Fly-links plugin.
Your new function can be implemented independently, as separate plugin.
And instead of using drawtools' function `import` better copy entities directly from `window.plugin.flyLinks.linksLayerGroup` and `window.plugin.flyLinks.fieldsLayerGroup` to `window.plugin.drawTools.drawnItems`.

**Comment by durck** [comment]
Ok, i will doing it. But where i can make request with new plugin?

**Comment by johnd0e** [comment]
Anywhere.
In separate PR, or even in this one.

**Comment by johnd0e** [comment]
Ref: #258

**Pull request closed without merging**
