### PR TITLE
Support Android's Themed app icons

### LINKED ISSUE #750: [Enhancement] Support Android's Themed app icons
It might be nice to have support for themed app icons on Android (supported from Android 13, API 33).

<details>
<summary>Example of such icons</summary>

Screenshot_2024-08-09-15-38-51-680_com miui home

</details>

It should be fairly simple to implement.

https://developer.android.com/about/versions/13/features#themed-app-icons
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add-to-your-app

### PR DESCRIPTION
**Pull request by kuci-JK**
This PR adds support for themed app icons in launcher. (Issue #750)

Screenshot_2024-08-09-16-55-53-692_com miui home

<details open>
<summary>All build variant icons here</summary

- Release:
Screenshot from 2024-08-09 16-55-02
- Beta:
Screenshot from 2024-08-09 16-54-55
- Debug:
Screenshot from 2024-08-09 16-54-48

</details>

close https://github.com/IITC-CE/ingress-intel-total-conversion/issues/750

### CODE REVIEW

**Comment by kuci-JK** [comment]
The Beta icon does not currently show the text in the monochrome variant.
I'll need to modify it slightly.
I am leaning into cutting out the purple area in the beta label and leaving only the text.
Something like this:
image


What do you guys think?

Is there somewhere the original app icon in svg or something so it would be easy to manipulate the layers and paths?

**Comment by modos189** [comment]
Everything we have is in the `assets` folder

Is there any possibility to reduce the transparency of additional diagonal lines in the test build?

**Comment by kuci-JK** [comment]
> Everything we have is in the `assets` folder

OK, I'll try to use that for tweaking the icon for beta version.

> Is there any possibility to reduce the transparency of additional diagonal lines in the test build?

I am not sure what do you mean can you provide a picture? I think the lines aren't transparent at all.

**Comment by Suburbanno** [comment]
I like

_just figma._

image

**Comment by modos189** [comment]
> I am not sure what do you mean can you provide a picture? I think the lines aren't transparent at all.

<details>
<summary>original test builds icon</summary>

IMAGE 2024-08-17 15:43:00

</details>

Now the diagonal lines are hardly visible because of the similar background color. But in your example of monochrome icons for test builds these lines stand out a lot and look ugly. Is there any possibility to make these lines less noticeable, like the original icons? If there is no possibility to change their transparency, then maybe make them thinner?

**Comment by kuci-JK** [comment]
Ok, I have updated the icons. The current state is:

debug:
- I have set the alpha to 0.5 for the diagonal lines

Screenshot from 2024-08-19 18-47-32
Screenshot from 2024-08-19 18-47-27

Screenshot from 2024-08-19 18-58-21
- New on the right, Previous on the left

beta:
- I have cut out the part behind the square with the text so it will be readable also in the monochrome icon variant

Screenshot from 2024-08-19 18-47-48
Screenshot from 2024-08-19 18-47-41

release:

Screenshot from 2024-08-19 18-47-58
Screenshot from 2024-08-19 18-47-54

Let me know what you think :)

**Comment by kuci-JK** [comment]
Android studio shows the thin line around the originally black pieces of the icon, but on the phone they are not visible as you can see in the screenshot here.
image

**Comment by Suburbanno** [comment]
@kuci-JK Can't the debug icon look like this?

image


btw, some icon packs only did the outline

[Arcticons-Team/Arcticons](https://github.com/Arcticons-Team/Arcticons/blob/main/app/src/normal/res/drawable-nodpi/iitcmobile.png)
[LawnchairLauncher/lawnicons](https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs%2Fiitc.svg)

**Comment by modos189** [comment]
> @kuci-JK Can't the debug icon look like this?

In this case, it's hard to tell from the icon if it's a beta or a test build
Also, I'd like to separate test builds more strongly from release and beta, as they are temporary builds intended only for testing a specific PR

**Comment by mxxcon** [comment]
> Ok, I have updated the icons.
> 
> Let me know what you think :)

In monochrome color theme the left and right filled in areas of the icon have a very faint light outline. Not sure if that's by design but it feels a bit like a glitch.

**Review by modos189 — APPROVED** [review]

**Pull request merged**
