### PR TITLE
Resizable dialogs (JqueryUI default)

### PR DESCRIPTION
**Pull request by le-jeu**
Current jquery code used by IITC allows resizable dialogs by default (`option.resizable: true`)
The dialog interface from IITC also handles resize event.

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/89175119cb195fe11b0ce6337564e38c91e6db54/core/code/dialog.js#L241

But the CSS for resize HTML handles is missing so it's not possible to resize dialogs yet.
This PR adds a minimal CSS to make those handles interactive.

### CODE REVIEW

**Comment by johnd0e** [comment]
What is the source of this css?

**Comment by le-jeu** [comment]
that would be https://github.com/jquery/jquery-ui/blob/main/themes/base/resizable.css

**Comment by johnd0e** [comment]
So let's include it as file, instead of inlining to `style.css`.

**Comment by johnd0e** [comment]
> that would be https://github.com/jquery/jquery-ui/blob/main/themes/base/resizable.css

Please include the url to https://github.com/IITC-CE/ingress-intel-total-conversion/blob/master/core/external/versions.md

**Review by johnd0e — APPROVED** [review]

**Review by modos189 — APPROVED** [review]

**Pull request merged**
