### PR TITLE
Adaptive Icon for android launcher icon

### PR DESCRIPTION
**Pull request by oldherl**
From Android Oreo (8.0), [Adaptive Icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) are used for App icons. 
I created the image assets for adaptive icon from /assets/IITC_square.svg , hope it fits well.

Screenshot:
compare

### CODE REVIEW

**Comment by modos189** [comment]
Thanks, good

Not relevant to this PR, just a thought. Because we are using the old method of accessing internal storage to store third-party plugins, it is impossible to move to Android API level 30, required for app updates on Google Play starting November 1, 2021 :( We'll have to do something about it

**Comment by oldherl** [comment]
Oh, but at least we can distribute outside Google Play, such as F-Droid or direct APK download, right?

**Comment by modos189** [comment]
Upload to F-Droid is not finished, but theoretically yes, it is possible

**Comment by johnd0e** [comment]
@oldherl 
What about another icon, used for test builds?
https://github.com/IITC-CE/ingress-intel-total-conversion/raw/master/mobile/app/src/debug/res/drawable-xxhdpi/ic_iitcm.png

**Comment by oldherl** [comment]
@johnd0e I don't know that icon. Where is it used?

**Comment by johnd0e** [comment]
It was used for test builds, but not after your patch https://iitc.app/build/test/IITC_Mobile-test.apk
Compare: https://iitc.app/build/test_archive/

**Comment by oldherl** [comment]
Now I understand the problem. I deleted that icon in my patch since I thought that icon was not used. I will further investigate how to convert that icon to Adaptive Icon.

**Comment by johnd0e** [comment]
@oldherl May be you could help with #218 also

**Pull request closed without merging**
