### PR TITLE
Fix update URL/downloadURL #32

### LINKED ISSUE #32: Scripts updateURL/downloadURL should not be empty
Scripts that are building for iitc.modos189.ru should have updateURL/downloadURL in order to self-update.

### PR DESCRIPTION
**Pull request by johnd0e**
WIP
Migration scripts for deployment in localbuildsettings.py
Fix  #32

### CODE REVIEW

**Comment by modos189** [comment]
this starts only for `test` branch, so I didn't send it to `master`

**Comment by modos189** [comment]
If only to combine history...

**Comment by johnd0e** [comment]
> this starts only for test branch, so I didn't send it to master

That's ok, as I've created this PR only for purpose of tracking in our Project#1.
And we can remerge it into `test-builds` multiple times, as it goes.

> If only to combine history...

What do you mean?

**Comment by johnd0e** [comment]
@modos189 
Should we keep this PR?
Or close it in favor of #97?

**Comment by modos189** [comment]
> Or close it in favor of #97?

Yes, we don't need it anymore

**Pull request closed without merging**
