### PR TITLE
escape macros in code in order to keep js-validity 

### LINKED ISSUE #50: @@-substitutions break validity of plugins' sources
Plugin's sources now are not valid js code, because of build-time substitution blocks like `@@METAINFO@@`, `@@PLUGINSTART@@`, `@@PLUGINEND@@`.

It complicates applying such tools like `eslint`.

It would be great if we could rearrange the code to make the substitutions appear commented, e.g.
```
// @@METAINFO@@
// ...
// @@PLUGINSTART@@
// ...
// @@PLUGINEND@@
```

### PR DESCRIPTION
**Pull request by johnd0e**
Fix #50.

Now all the sources are completely valid js,
that could be processed by external tools, such as eslint.

/ to be discussed before merge /

### CODE REVIEW

**Comment by johnd0e** [comment]
Well, now I do not like these 'garbage' comments in built files..

**Comment by johnd0e** [comment]
Well, now I'm pretty happy with this PR.

@modos189 
What do you think?

**Comment by modos189** [comment]
Why INCLUDESTRING and INCLUDEIMAGE not updated?

**Comment by johnd0e** [comment]
They do not require escaping as typically applied inside of strings, thus already escaped by quotes.

```
  $('<style>').prop('type', 'text/css').html('@@INCLUDESTRING:plugins/distance-to-portal.css@@').appendTo('head');

```

**Comment by modos189** [comment]
Then all is well. When merge? I don't quite understand the new scheme yet.)

**Comment by johnd0e** [comment]
> When merge?

Well, I've already merged it in my 'develop' branch)
But still wants to work more with this setup to make completely sure than no bugs added.

> I don't quite understand the new scheme yet.)

So let's discuss it.
May be there is even better solution.

**Comment by johnd0e** [comment]
I think that we can completely avoid these macros in plugin sources:
* `@@METAINFO@@` is always placed right before `// ==/UserScript==`
* `@@PLUGINSTART@@` is always right after `// ==/UserScript==`
* `@@PLUGINEND@@` is always near EOF.
* `@@DATETIMEVERSION@@` is near `@version` EOL.
* `@@BUILDNAME@@-@@BUILDDATE@@` is not useful anyway.

**Pull request closed without merging**
