### PR TITLE
portalslist: add scout/capture/visit filters

### PR DESCRIPTION
**Pull request by le-jeu**
- `All` filter is hidden on desktop, reselect the active filter to disable it 
- includes scout/capture/visit filters
- rework some portalslist functions 
- UI filters: 3 columns on desktop/landscape(mobile) and 2 columns on portrait (mobile) 
- increase description font size 
- fix V/C&S UI size 

image

image

image

~This need to be rebased before merging~

### CODE REVIEW

**Comment by johnd0e** [comment]
Rebase?

**Review by modos189 — CHANGES_REQUESTED** [review]
For some reason text on my header and footer are black on my mobile, which makes it hard to distinguish the text.

изображение

Also, it would be nice to add some extra space to the right of the last column, so that the content doesn't end up flush with the border of the table.

**Comment by johnd0e** [comment]
> For some reason text on my header and footer are black on my mobile

Perhaps because of https://github.com/IITC-CE/ingress-intel-total-conversion/pull/497/commits/94e91299be006b810901f70cf8274fdd63d3ccb7

**Review by modos189 — APPROVED** [review]

**Comment by johnd0e** [comment]
Several incompatibilities with KitKat (and old iOS) were found.
The major is lack of [grid support](https://caniuse.com/?search=css%20grid).

Imho it's not important to have the same appearance on those legacy systems, but it should be functional at least (some visual defects are acceptable).

**Comment by le-jeu** [comment]
On KitKat (or webview not supporting grid layout)
image

Using 708a0d9
image

**Pull request merged**
