### PR TITLE
[Mobile] Add missing dependency

### PR DESCRIPTION
**Pull request by McBen**
current mobile won't compile 'cause missing dependency

### CODE REVIEW

**Comment by johnd0e** [comment]
> current mobile won't compile

https://travis-ci.org/github/IITC-CE/ingress-intel-total-conversion/builds/752264208#L2462
```
BUILD SUCCESSFUL in 1m 14s
```

**Comment by McBen** [comment]
I can't say anything about your configuration.
Out-of-the-box I'll get:
grafik

**Comment by johnd0e** [comment]
@modos189

**Comment by johnd0e** [comment]
Superseded by #431.

**Pull request closed without merging**
