### PR TITLE
Fix: Portal info: layout breaks down it title is long #44

### PR DESCRIPTION
**Pull request by modos189**

### CODE REVIEW

**Comment by johnd0e** [comment]
This solution has limitations.
The problem is that the line contain not only `title` but also 1-2 other elements (and some plugins may require to add even more)...

**Comment by modos189** [comment]
I tested on two elements. Of course, this is not best way, but now plugins do not have method of adding icons, which leads to such situations. We do it right in the future, in a new design

**Comment by johnd0e** [comment]
What if we put the title with all attached icons into additional container like here https://github.com/johnd0e/ingress-intel-total-conversion/commits/portal-info-fix
(unfinished) 

**Edit**
Failed to get ellipsis this way.

**Comment by johnd0e** [comment]
Alternative patch: #83 
It handles title length more correct, and does not depend on number of attached icons (and their widths).

**Comment by modos189** [comment]
best way: https://github.com/IITC-CE/ingress-intel-total-conversion/pull/83

**Pull request closed without merging**
