### PR TITLE
A significant increase in performance of map with clusters

### PR DESCRIPTION
**Pull request by modos189**
Partial solution of issue #143

Now ornaments are drawn as circleMarker on canvas.

### CODE REVIEW

**Comment by johnd0e** [comment]
What if we make plugin for this?

**Comment by modos189** [comment]
Noo. Why?

Only a small number of users will know about problem and turn on plugin, but most users if they open area with a lot of ornaments will receive a stop responding mobile application (at least, I have so) and will swear what a bad IITC.

**Comment by johnd0e** [comment]
Ok.
Compare my implementation https://github.com/johnd0e/ingress-intel-total-conversion/commit/e9e82e12c0ef489b86716cc43e928662be2c20f4

**Comment by modos189** [comment]
Your implementation is very good, but new PR https://github.com/IITC-CE/ingress-intel-total-conversion/pull/181 is better )

**Pull request closed without merging**
