### PR TITLE
IITC Mobile: Improvements to the debug window

### PR DESCRIPTION
**Pull request by modos189**
* New console messages appear from bottom of screen;
 * Odd and even messages are different in color;
 * New messages appear with an animation effect.
 * Console message list only scrolls automatically if user is viewing the end of page.
 * Added a button to scrolling to the end of debug messages.
 * Added buttons to scrolling to the end of debug messages; to move through the history of entered in commands debug; to move cursor in input field.

<details>
<summary>first commit</summary>

preview

</details>

<details>
<summary>last commit</summary>

preview

</details>

### CODE REVIEW

**Comment by johnd0e** [comment]
@modos189 👍

**Review by johnd0e — CHANGES_REQUESTED** [review]
Could you make 'command line' font smaller?

**Comment by modos189** [comment]
img

**Comment by modos189** [comment]
Screenshot_20200306_185626

**Comment by modos189** [comment]
<details>
<summary>Screenshot</summary>

Screenshot_20200503-015147_IITC_Mobile_Test

</details>

**Pull request merged**
