### PR TITLE
fix-googlemap-china-offset: refactoring

### PR DESCRIPTION
**Pull request by johnd0e**
divide PRCoords into 2 distinct functions:
* plugin.fixChinaOffset.isInGoogle
* plugin.fixChinaOffset.gcjObfs

### CODE REVIEW

**Comment by johnd0e** [comment]
Oops, I will resubmit the PR..
You've changed filename and id, and this is not that simple, as you should leave stub (meta) for updating old version.

Also, if you change id, than better drop the part after `@`
`iitc-plugin-fix-china-offset@breezewish` --> `iitc-plugin-fix-china-offset`

(So as for me than easier to revert rename)

**Comment by modos189** [comment]
I agree. Will you do?

**Comment by johnd0e** [comment]
You mean I will rename it back in my PR?

**Comment by modos189** [comment]
Changes move to `fix-china-offset`, but create file-dummy `fix-googlemap-china-offset`.

Or I can do it

**Comment by johnd0e** [comment]
Done, but not tested (hurry right now).
I propose rename `fix-china-offset` to `basemap-fix-china-offset` or `fix-china-map-offset`.

**Comment by johnd0e** [comment]
Parent issue: #64

**Pull request merged**
