### PR TITLE
fix 'build' badge in README.md

### LINKED ISSUE #98: v0.29
@modos189
So what features do you want to include in nearest release?
Would you like to use Project#1 to track the progress?

### PR DESCRIPTION
**Pull request by modos189**
fix 'build' badge https://github.com/IITC-CE/ingress-intel-total-conversion/issues/98#issuecomment-477723056

### CODE REVIEW

**Comment by johnd0e** [comment]
1. I've updated description 'cause former notation has special action (autoclose corresponding issue), which is not relevant in this case, and #98 still has unresolved questions.

2. I do not think that proposed fix is right.
Our main branch is `master` and I suppose that badge should display `master`'s build state.

**Comment by modos189** [comment]
1. I updated the description in the telegram channel, but forgot to report it.

2. `master` branch is not used for building, and it always contains a working version, as it is a release version.

**Comment by johnd0e** [comment]
> 2\. `master` branch is not used for building, and it always contains a working version, as it is a release version.

Exactly: it is release version.

If we decide to use badge for some other branch - it should be explicitly pointed.

BTW, currently this badge is not useful, because our build system lacks tests.
Badge shows success even when there are errors preventing from page loading.
(the same apply to docs badge)

**Comment by johnd0e** [comment]
> 1. I updated the description in the telegram channel, but forgot to report it.

But iitc site also need this warning.
And I even think we should keep it there pinned at least several months.

**Comment by johnd0e** [comment]
Something wrong:
image

Why 2 badges?

**Comment by modos189** [comment]
Because you opened Diff. Correct link: [README.md](https://github.com/IITC-CE/ingress-intel-total-conversion/blob/628dd1d06d5b1e19ec84f4961b0796fd574d4476/README.md)

**Comment by johnd0e** [comment]
Ok then. Let's merge it soon.

**Pull request merged**
