### PR TITLE
Safe removal of hooks

### PR DESCRIPTION
**Pull request by McBen**
### Problem:
if a hook is removed in an event handler the 'runHook' loop get out of sync.

Example error code:
```
addHook("portalDetailsUpdated",  myHook);  
addHook("portalDetailsUpdated",  anotherHook); // this one will be skipped and runHook will try to call "undefined"

myHook = (e) => {
  removeHook("portalDetailsUpdated",  myHook);
}
```

### (possible) Solution
Create a copy of the hook-array.
The old runHook loop will stick with the old array.
Show a warning for developers because this will be still a problem in old iitc versions.

### CODE REVIEW

**Comment by johnd0e** [comment]
> Create a copy of the hook-array.

Seems reasonable.

And in future we are going to deprecate old homebrew hooks implementation in favor of Leaflet events. **Edit**: https://github.com/IITC-CE/ingress-intel-total-conversion/issues/217#issuecomment-800317584

**Comment by cloudkucooland** [comment]
@johnd0e Thank god.

**Comment by johnd0e** [comment]
> in favor of Leaflet events.

Leaflet event system may be not directly applicable:
- There is no arguments control, so such errors will not be reported:
  - Callback must be a function
  - Callback wasn\'t registered for this event.
- When firing event - handler call is not wrapped in `try/catch`

**Comment by johnd0e** [comment]
> Create a copy of the hook-array.
> The old runHook loop will stick with the old array.

I've inspected [similar functionality of Leaflet](https://github.com/Leaflet/Leaflet/blob/0f904a515879fcd08f69b7f51799ee7f18f23fd8/src/core/Events.js#L147-L168), and found that it is slightly reliable, as it covers 2 more cases:
- `runHook` may be nested
- it's safer to suppress removed hook handler with noop to prevent it's calling in some edge cases.

See: #462.

> Show a warning for developers because this will be still a problem in old iitc versions.

Well, I do not feel that anybody should care old iitc versions.

**Pull request closed without merging**
