### PR TITLE
Fix performance drop when displaying a large number of ornaments 

### LINKED ISSUE #143: Performance issues
When we have a lot of features active on map - leaflet performance degrades dramatically.

It's really hard to use map with a lot of portals. And it prevents us to work on #121 (and similar).

It's not clear yet what is the main source of performance lost.
I'm pretty sure that it's not portal markers themselves, as `L.CircleMarker` uses _Canvas_ renderer.

For start, here are some known solutions:
- https://github.com/cyrilcherian/Leaflet-Fullcanvas
- https://github.com/eJuke/Leaflet.Canvas-Markers
- https://github.com/yakitoritabetai/Leaflet.LabelTextCollision

Related issue: #129

### PR DESCRIPTION
**Pull request by modos189**
Fix #143: draw on canvas (instead of multiple markers) with [Leaflet.Canvas-Markers](https://github.com/Spaction/Leaflet.Canvas-Markers) (forked from https://github.com/Spaction/Leaflet.Canvas-Markers)

### CODE REVIEW

**Comment by johnd0e** [comment]
But to test it thoroughly we need to wait next Niantic event

**Comment by modos189** [comment]
I don't think so, because types of ornaments have long been known and described in header of `code/ornaments.js`

**Comment by johnd0e** [comment]
It's not only about ornaments icons, bot more about new canvas markers (I have not tested it in time, and now ornaments gone)

Also I see in the PR uncommon leaflet usage patterns which I'd like to fix.

**Comment by modos189** [comment]
Other types of markers can be used for this purpose. For example, I found in Tokyo frackers that are active right now.
https://intel.ingress.com/intel?ll=35.709534,139.721353&z=19

Due to the fact that all types of markers are known, it is possible to replace icons for testing other layers.

up: Beacon here: https://intel.ingress.com/intel?ll=35.711199,139.781713&z=17

**Comment by johnd0e** [comment]
> I found in Tokyo frackers that are active right now.

I would prefer to test it with conditions similar to those we saw yesterday: huge ornaments amount.

**Comment by johnd0e** [comment]
Please enable Issues section for https://github.com/IITC-CE/Leaflet.Canvas-Markers repo.

**Comment by modos189** [comment]
Add
`portal.options.data.ornaments = ['ap4'];`
before
`if (portal.options.data.ornaments) {`
to mark ALL portals as clusters

**Comment by modos189** [comment]
> Please enable Issues section for https://github.com/IITC-CE/Leaflet.Canvas-Markers repo.

done

**Comment by johnd0e** [comment]
> Add  `portal.options.data.ornaments = ['ap4'];`

See screenshot:
<details>

image

</details>
 
More than a half of map is without ornaments.
How to reproduce: make narrow window, reload IITC, then maximize window.

P.S. May be better discuss it in corresponding repo.

**Comment by modos189** [comment]
I added canvasIconLayer to LayerGroup() because no all functions are implemented. Disable the layer and reload the page. The layer will be enabled again.

**Comment by johnd0e** [comment]
> I added canvasIconLayer to LayerGroup() because no all functions are implemented.

So let`s implement all.

BTW, there are still errors in console:
<details>

```
Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
    at <anonymous>:15322:15835
    at a (<anonymous>:15322:1327)
    at remove (<anonymous>:15322:3508)
    at NewClass._removeGeneric (<anonymous>:15322:15973)
    at NewClass.removeMarker (<anonymous>:15322:15790)
    at NewClass.removeLayer (<anonymous>:15322:15639)
    at <anonymous>:19710:34
    at Array.forEach (<anonymous>)
    at Object.window.ornaments.removePortal (<anonymous>:19707:37)
    at window.Render.deletePortalEntity (<anonymous>:18534:22)
```
Similar: https://github.com/IITC-CE/Leaflet.Canvas-Markers/issues/8
</details>

I propose to include unminified plugin sources in order to debug such cases.

**Comment by modos189** [comment]
> So let`s implement all.

Layers are turned on and off in this function. But I don't know how to implement support.

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/256f9c53a866a254b40e40b1f766e58b4d2a89f4/code/boot.js#L541-L565

**Comment by johnd0e** [comment]
> Layers are turned on and off in this function. But I don't know how to implement support.

I suppose it's a matter of events support.
E.g. `layer.on('remove',function () { alert() })` should work with every leaflet layer.

**Comment by johnd0e** [comment]
Ok, I've found the source of our issue: https://github.com/Spaction/Leaflet.Canvas-Markers/blob/master/src/plugin/leaflet.canvas-markers.js#L270

Perhaps that was implemented wrong.
If we comment out this method then our layer keep it's state after page reload.

**Comment by johnd0e** [comment]
@modos189 
Please check if you are OK with latest refactoring
(this PR is not best place for such things, so later I am going to rebase it)

**Comment by modos189** [comment]
Looks good. We also need to add links to new libraries in ATTRIBUTION.md

**Comment by johnd0e** [comment]
Branch rewritten!

Will update ATTRIBUTION.md after #134

Todo: finish https://github.com/IITC-CE/Leaflet.Canvas-Markers/

**Comment by modos189** [comment]
Looks like some kind of change was lost in rewrite process: `ReferenceError: module is not defined`

**Comment by johnd0e** [comment]
`boot.js` wasn't staged for last commit. I will fix it tomorrow

**Comment by modos189** [comment]
I'll have to wait, couldn't fix it(

**Comment by johnd0e** [comment]
See `boot.js` here aa9fea57966db4c8ab00b9ed86e3e25c14b235bb

**Comment by modos189** [comment]
Fatal error in greasemonkey:

```ReferenceError: event is not defined```

**Comment by johnd0e** [comment]
What is the source of this reference?

**Comment by modos189** [comment]
It's hard to say because the commit history has been rewritten(

**Comment by johnd0e** [comment]
I mean in what source file this `event` is referenced?

**Comment by modos189** [comment]
Please check https://github.com/IITC-CE/Leaflet.Canvas-Markers/pull/1/commits/e0bc449cbf28071d55649dfe130c4b877600b6fc#r280502665

**Comment by johnd0e** [comment]
Fixed.
`leaflet.canvas-markers.js` is from `test` branch.

**Comment by johnd0e** [comment]
Look to the intel with DevTools.
And you see that this PR is far from ready(

**Edit**
I've fixed several errors.

**Comment by modos189** [comment]
So, what does it take to complete this PR?

**Comment by johnd0e** [comment]
https://github.com/IITC-CE/Leaflet.Canvas-Markers/commit/71eab756484bf298384f5059f15d2fd86fb0b182#commitcomment-33502466

**Pull request merged**
