### PR TITLE
Show linked portals improve

### PR DESCRIPTION
**Pull request by johnd0e**
* portal images fill full width
* on taphold: text instead of portal pic
* last viewed portal is highlighted
* on mobile:
  - single tap to show tooltip
  - double tap to go to portal
* on taphold: improved 'show link on map' function 
* picture in tooltip
* tooltip now updates on new data coming
* style tweaks
* minor bug fixed

### CODE REVIEW

**Comment by johnd0e** [comment]
There is minor cosmetic issue left: on click/hover over `outOfRage` div - it gets re-rendered with updated data, but we still see old tooltip, which has `Go to portal` instead of real portal title.
Now investigating if it's easy to reopen tooltip with updated content..

This code works:
```
$('.ui-tooltip-content').html(div.attr('title')); // update tooltip with new content
```
But I feel that it is terribly wrong...

**Review by modos189 — APPROVED** [review]

**Comment by johnd0e** [comment]
1 more issue left to fix.
After https://github.com/IITC-CE/ingress-intel-total-conversion/commit/59cc3126bd85f5c9e298e94517384b34c8458d65 some styles had changed, so upper portals' boxes are out of bounds of the main portal's picture.

**Comment by johnd0e** [comment]
Is it possible to merge the PR but still leave it opened?

**Comment by modos189** [comment]
No. We can still leave opened

**Comment by johnd0e** [comment]
@modos189, please check last commit (`portal images fill full width`)
Are images look better now?
Or I should revert it?

**Comment by modos189** [comment]
Good, but just need to add a property
```z-index: 1;```
in
```.showLinkedPortalLink.incoming::before, .showLinkedPortalLink.outgoing::before```

To show icons of link direction

**Comment by johnd0e** [comment]
@modos189, fixed.
And what do you think about border-radius and box-shadow?

**Comment by modos189** [comment]
Then I suggest to add
```background: #00000080;```
to be seen against the background of bright photos.

And all prefixes like `-webkit-border-radius` must be specified before the announcement `border-radius`

**Comment by johnd0e** [comment]
> Then I suggest to add `background: #00000080;`

Well, after some experiments I tend to think that these symbols are hard to see and use as they are ambiguous.
I have another proposition: after all, we care only _outgoing_ links (as they are limited). So wouldn't it better to mark outgoing only?

Please check if you like transparent containers (in latest commit).

P.S.
After that I want to test other concepts:
- Portal info (text) instead of images
- Portal info over the images (which have to be semi-transparent in order to keep text readable)

**Comment by modos189** [comment]
> I have another proposition: after all, we care only outgoing links (as they are limited). So wouldn't it better to mark outgoing only?

It would be handy as a setting, but by default it would be misleading

> if you like transparent containers

like

**Comment by johnd0e** [comment]
> It would be handy as a setting, but by default it would be misleading

Why misleading?
Several days ago we have no symbols at all, tomorrow we'll get some symbol over outgoing.
It couldn't be misleading, as there are also clear text labels incoming/outgoing.

**Comment by modos189** [comment]
I thought you were suggesting not displaying incoming links at all. But since it is only about the icon, I agree not to display it for incoming.

**Comment by johnd0e** [comment]
> show-linked-portals: more bold symbol

Actually I'm not sure that symbol is good.
And we also need to play with it's position (in order to not interfere with text).

**Pull request merged**
