### PR TITLE
Automatic sending of IITC-Mobile app to Google Play

### PR DESCRIPTION
**Pull request by modos189**
Added master branch build and automatic sending of IITC-Mobile app to Google Play in Beta status.

Refusing to use number of commits as versionCode due to possibility of reducing the number of versionCode, which requires reinstalling android application. Using a date to within 10 seconds as versionCode.

### CODE REVIEW

**Comment by modos189** [comment]
Disabled Proguard for debug build (was erroneously enabled in this PR). Got following run time results:

test - proguard off - 2.7Mb
beta - proguard on, without optimizations - 1.9Mb
release - proguard on, with optimizations - 1.6Mb

assembly time comparison
(after each assembly I cleaned _mobile/app/build/*_)

I haven't noticed any difference in debugging.

**Comment by johnd0e** [comment]
Todo:
- [ ] Adapt badges in README.MD

**Comment by modos189** [comment]
Tests with the current master:
test - proguard off, without optimizations - 4.6MiB
beta - proguard on, without optimizations - 2.7MiB
release - proguard on, with optimizations - 2.4MiB

For comparison, size of apk release v0.30.1 is 2.3MiB

**Comment by johnd0e** [comment]
> For comparison, size of apk release v0.30.1 is 2.3MiB

Just for record: comparing with table in [previous](https://github.com/IITC-CE/ingress-intel-total-conversion/pull/305#issuecomment-573290242) post we see that optimized apk size increased by 50% (from 1.6MB to 2.4MB).
This is the impact of merging #323.

**Review by johnd0e — APPROVED** [review]

**Pull request merged**
