### PR TITLE
Region Scoreboard Enhances

### PR DESCRIPTION
**Pull request by angel93ayora**
Added texts for:
TEAM leads by N
N checkpoints remaining
Next checkpoint:    DATE
Cycle ends:    DATE

Improved the table to show accumulated MUs and difference in MUs with previous checkpoint

### CODE REVIEW

**Comment by johnd0e** [comment]
Hi!
We [are going](#2) to merge this: https://github.com/iitc-project/ingress-intel-total-conversion/pull/1045 (by original author of the plugin).

What do you think about it?
Is your patch applicable in this case?

**Comment by angel93ayora** [comment]
I like https://github.com/iitc-project/ingress-intel-total-conversion/pull/1045 i can implement my changes along with them.

**Comment by angel93ayora** [comment]
Should i commit to this PR including the changes of https://github.com/iitc-project/ingress-intel-total-conversion/pull/1045 ??

**Comment by johnd0e** [comment]
> Improved the table to show accumulated MUs and difference in MUs with previous checkpoint

Could you attach sample screenshot here?

> Should i commit to this PR including the changes of [iitc-project/ingress-intel-total-conversion#1045](https://github.com/iitc-project/ingress-intel-total-conversion/pull/1045) ??

Make PR vs [`scoreboard-improved`](https://github.com/IITC-CE/ingress-intel-total-conversion/tree/scoreboard-improved) branch.

**Comment by angel93ayora** [comment]
> Could you attach sample screenshot here?
Yes, i thought i've uploaded one

2019-04-29 00_22_00-Ingress Intel Map

this is with enlarged width (+30px)

image
this is with original width

i think it'll be tighter and more readable to make numbers shorter with K / M suffixes, example: 1.5M MU

**Comment by johnd0e** [comment]
Someone may need full unshortened values..

I have an idea: what if your new table data would be optional?
And we could turn it on via checkbox, or just longtap

**Comment by angel93ayora** [comment]
> Someone may need full unshortened values..

them can be put on a title attribute


> I have an idea: what if your new table data would be optional?
> And we could turn it on via checkbox, or just longtap

you mean to switch full values vs short?

i could do two switchable views, compact and full

**Comment by johnd0e** [comment]
> them can be put on a title attribute

It is hardly accessible for touch devices


> you mean to switch full values vs short?

I mean `full without diff` vs `short with diff`

**Comment by angel93ayora** [comment]
so it could be:

compact
- short numbers
- cp# | cp_score | diff

full:
- full numbers
- cp# | cp_score | summatory

or togglers for each column, this can be done easy with css

**Comment by johnd0e** [comment]
> cp# | cp_score | diff

IMHO 'diff' does not have much sense without 'summatory', so I mean `cp# | cp_score | summatory | diff`

And looking again to this.. Is that 'diff' really useful? Could you explain?

**Comment by angel93ayora** [comment]
> And looking again to this.. Is that 'diff' really useful? Could you explain?

i.e when you made some fields before check and you want to know how much they scored

summatory is probably less useful:
i.e when you want to know how much MUs are needed to win a cycle, but only last summatories are useful in this case

**Comment by johnd0e** [comment]
Probably I understand wrong.
There are 3 columns on your screenshot: Sum. | Score | Diff.

1. We need Sum: it's historic value for every checkpoint
2. Score gain seems useful too
3. Diff is difference between last and next Score gains
   Actually I do not see how I could use this precise values.

**Comment by angel93ayora** [comment]
diff numbers are the best metric for measuring MU activity in comparison with previous checkpoint

> i.e when you made some fields before check and you want to know how much they scored

or when you destroy some fields and want to see how much mu you destroyed (aprox. because other players may have built/destroyed some fields)

**Comment by johnd0e** [comment]
> diff numbers are the best metric for measuring MU activity in comparison with previous checkpoint

It's not clear why should we compare with prev. CP, why not with average gain, or some other random metric.

> or when you destroy some fields and want to see how much mu you destroyed (aprox. because other players may have built/destroyed some fields)

Here you mean Score column, right?

**Comment by angel93ayora** [comment]
>It's not clear why should we compare with prev. CP, why not with average gain, or some other random metric.

because it (diffs) reflects the MU variation on the previous 5h


>>or when you destroy some fields and want to see how much mu you destroyed (aprox. because other >>players may have built/destroyed some fields)

>Here you mean Score column, right?

here i meant diff column also

yes, you can figure out what was the increase/decrease of MUs comparing with the previous checkpoint, the diff column is that but you dont have to subtract scores in your mind

**Comment by angel93ayora** [comment]
i've seen that it is already done on the graphic, so i'll delete it on the table in order to save width pixels. Also it's not clear if it is useful.

**Comment by angel93ayora** [comment]
Closed, i'll PR from a branch forked from https://github.com/iitc-project/ingress-intel-total-conversion/pull/1045

**Pull request closed without merging**
