### PR TITLE
Added argument to start web server after build

### PR DESCRIPTION
**Pull request by modos189**
This change will allow in browser extension IITC-Button select a local repository to work with it. Once the build is complete, the changes in IITC and plugins are immediately available in the browser, making it easier to debug.

UP:

Example of use:
`python web-meta-run.py local` (start on port 8000)
or
`python web-meta-run.py local --port=1331`

Will be created file local.json and will be started simple webserver

### CODE REVIEW

**Comment by modos189** [comment]
Actually, this is main reason why I decided to create IITC-Button extension. For now there is no easy and fast way to test changes in IITC and plugins.

**Comment by johnd0e** [comment]
> For now there is no easy and fast way to test changes in IITC and plugins.

But you was always able to use local webserver + grease/tampermonkey, wasn't you?

What is the purpose of that extension?

**Comment by modos189** [comment]
> you was always able to use local webserver + grease/tampermonkey

Partially. 
You cannot change the update channel from release to local updates. You must remove all release scripts and manually install the local ones.
Back - the same procedure.
In addition, running your own web server reduces threshold for entry into the development.

These problems are solved by extension. In addition, the IITC-Button extension makes it easy to include any plugins by selecting them in categories.

**Comment by johnd0e** [comment]
> You must remove all release scripts and manually install the local ones.

It's true.

> In addition, running your own web server reduces threshold for entry into the development.

Well, here I do not agree as every developer needs python to build from sources.

> In addition, the IITC-Button extension makes it easy to include any plugins by selecting them in categories.

BTW, instead of python server I use this https://github.com/McBen/ingress-intel-total-conversion/blob/master/fileserver.js
And it provides categorized view.

P.S.
I'd like to try this new easy-button extension. Do you have chrome version?
I do not need it in webstore, just raw sources.

**Comment by modos189** [comment]
> just raw sources

In the adjacent repository: https://github.com/IITC-CE/IITC-Button

**Comment by johnd0e** [comment]
Just tried it. It's really more user-friendly that grease/tampermonkey.
I found how to change update channel, but there is no `local` option.

**Comment by johnd0e** [comment]
About PR itself.
I have not saw the result in action yet (will try soon), but have 3 preliminary thoughts:
- what if we make `webserver` not commandline arg, but property of build target (buildsettings.py/localbuildsettings.py)
- alternatively: make webserver independent from build.py, to be able to run it in any moment.
  * Ideally: not to be tied to build process, but listen for folder changes instead.
  * or generate .json for any build, unconditionally, then we will be able to run server later.

**Comment by modos189** [comment]
> I found how to change update channel, but there is no local option.

I will add this feature soon

> what if we make webserver not commandline arg, but property of build target

Well, that's one way to do it.

**Comment by johnd0e** [comment]
1.
   ```
   Update channel "local" opened. Start a web server on port 8000
   Last generation of categories: 2019-05-20 15:30:44 UTC
   Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
   ```
   Is this message about `0.0.0.0` correct?

2. In fact I'm able to open `http://localhost:8000/`, but then I see full `iitc-ce` repo root directory listing.
    Is it intended?

3. This script creates json in repo root, but why not in `build/*`?
    Imho it'd be more natural. And no need to generate file if it is already there.

4. We can skip settings reading, as all built targets are already in `build/*`

5. Instead of `update_meta` worker it would be simpler to generate json on build, unconditionally.
   For maintainability may be better left code in separate file, and call it from `build.py`.

**Comment by johnd0e** [comment]
BTW, wouldn't it more consistent to do it in IITC-Button itself?
- we start server in needed directory
- iitc-button makes json list, and keep it updated (looking for `.build-timestamp`)

**Comment by modos189** [comment]
> Is this message about 0.0.0.0 correct?

It's Ok, it means that access is open from all local addresses. https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

> but then I see full iitc-ce repo root directory listing.

Yeah, that's the way it's supposed to be. Well, it's enough to display only `build` and `*.json`, but I don't see any security threats here.

> This script creates json in repo root, but why not in build/*?

This is exactly how it is done by analogy with the architecture of the site. But this is a good idea.

> wouldn't it more consistent to do it in IITC-Button itself

I tried to do it same as downloading updates from site. It would be excessive to download updates of .meta.js files every time for all plugins, including those that are disabled.

**Comment by johnd0e** [comment]
> I tried to do it same as downloading updates from site. It would be excessive to download updates of .meta.js files every time for all plugins, including those that are disabled.

Do you mean that same json is generating for release/test-builds on iitc.modos189.ru?

**Comment by modos189** [comment]
Yeap https://iitc.modos189.ru/release.json

**Comment by johnd0e** [comment]
> Yeah, that's the way it's supposed to be. Well, it's enough to display only `build` and `*.json`, but I don't see any security threats here.

So I propose:
- put json files into target directories, so background `worker` become unneeded.
- expose only target directory, as it is enough.

Alternatively, we can expose whole `build` directory, and implement target switching in IITC-Button.

**Comment by johnd0e** [comment]
> I tried to do it same as downloading updates from site. It would be excessive to download updates of .meta.js files every time for all plugins, including those that are disabled.

I have another opinion.
- meta files are tiny enough, and every other userscript manager downloads them all every time.
- still we can avoid of unneeded downloads looking for `.build-timestamp` (download meta only when `.build-timestamp` changes)

I certainly do not insist, and you may continue using json, but IMHO it is just excessive intermediate entity.

**Comment by modos189** [comment]
Other userscripts managers download .meta.js only for active (or installed) plugins. We have task of downloading meta files for all plugins. 58 requests for only plugins just to check updates? Including the fact that the connection may be unstable.

**Comment by johnd0e** [comment]
> 58 requests for only plugins just to check updates?

No. Just 1 request, to get `.build-timestamp`

**Comment by modos189** [comment]
Ok, when update 58 requests + on request for each installed plugin. Or make it even more difficult to request only meta.js file for uninstalled plugins and user.js for installed plugins. All this is too complicated, provoking errors and a large number of requests.

**Comment by johnd0e** [comment]
> Ok, when update 58 requests

Well, it's 40 KB uncompressed.

> request only meta.js file for uninstalled plugins and user.js for installed plugins.

Considering that IITC-Button is mostly for desktop, I would update all plugins at once, including uninstalled. It is 930 KB, or ~200 KB zipped.

> All this is too complicated, provoking errors and a large number of requests.

I see it opposite, as more simple approach)

**Comment by modos189** [comment]
It's time to get back to work :)

**Comment by Suburbanno** [comment]
Go guy!! excited for new release!!

**Comment by johnd0e** [comment]
I have not viewed last commits yet, but please note: we have some unmerged PRs for `build.py` that may (and will) conflict with this PR (no problem, but better merge this last).

**Comment by johnd0e** [comment]
Instead of `web-meta-run.py` I propose to use `postBuild` action provided in `buildSettings`.

**Pull request closed without merging**
