### PR TITLE
external: Update Leaflet.GridLayer.GoogleMutant to v0.11.3

### LINKED ISSUE #151: margin-bottom issue with .leaflet-bottom
See `#map > div.leaflet-control-container > div.leaflet-bottom.leaflet-left` (and the same is with `.leaflet-right`)

If current baselayer is any of GoogleMutant - `.leaflet-bottom` element has inline style:
```
<div class="leaflet-bottom leaflet-left" style="margin-bottom: 20px;">
```

In other layers you see the same but with `margin-bottom: 0em`.

Because of this fact during layer switching you can see that position of bottom leaflet controls changes (e.g. see minimap).

### LINKED ISSUE #293: scale bar is hidden on mobile
With any basemap except ingress/google scale bar get hidden under statusline.

* Complete solution: fix map container bounds, or `.leaflet-bottom` style, considering related issues #89, #151

* Just quick fix: set `plugin.scaleBar.mobileOptions.position` to `topleft`.

### PR DESCRIPTION
**Pull request by johnd0e**
- external: update Leaflet.GridLayer.GoogleMutant to v0.11.3
- #311 reverted, as it has been resolved [alternatively](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/merge_requests/49) in upstream: 

Fix #151, #293

Note:
- Starting with v0.11.0, the code relies on `Symbol` and `Map`.
  IE11 and [browsers that don't support `Symbol`](https://www.caniuse.com/mdn-javascript_builtins_symbol)
  or [don't support `Map`](https://www.caniuse.com/mdn-javascript_builtins_map) also need polyfills to work

### CODE REVIEW

**Comment by johnd0e** [comment]
Note:
-   Starting with v0.11.0, the code relies on `Symbol` and `Map`. IE11 and [browsers that don't support `Symbol`](https://www.caniuse.com/mdn-javascript_builtins_symbol) or [don't support `Map`](https://www.caniuse.com/mdn-javascript_builtins_map) also need polyfills to work.

**Comment by modos189** [comment]
After this change on IITC Mobile, part of the attribution is displayed in minimap. Can this be fixed?
image

**Comment by johnd0e** [comment]
@modos189 
Good catch!
Observed only in mobile view.
Should be easy to fix.

**Comment by johnd0e** [comment]
@modos189 
Check now

**Review by modos189 — APPROVED** [review]

**Pull request merged**
